/shared5/studentprojects/Qikai/Horse_database/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2731058_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2731059_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2731060_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2731061_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1545181_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1545182_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2179547_sort.bam \
    --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1545190_sort.bam \
    --referenceFasta /shared5/studentprojects/Qikai/Horse_database/EquCab3_ref/GCF_002863925.1_EquCab3.0_genomic.fna \
    --runDir Result_Holsteiner