/shared5/studentprojects/Qikai/Horse_database/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py \
    1. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527952_sort.bam \
    2. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527953_sort.bam \
    3. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527954_sort.bam \
    4. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988141_sort.bam \
    5. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507062_sort.bam \
    6. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507085_sort.bam \
    7. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978596_sort.bam \
    8. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979784_sort.bam \
    9. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978597_sort.bam \
    10. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979785_sort.bam \
    11. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988159_sort.bam \
    12. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507084_sort.bam \
    13. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978598_sort.bam \
    14. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979786_sort.bam \
    15. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988162_sort.bam \
    16. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507083_sort.bam \
    17. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527971_sort.bam \
    18. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988161_sort.bam \
    19. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507082_sort.bam \
    20. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527955_sort.bam \
    21. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988164_sort.bam \
    22. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507081_sort.bam \
    23. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527956_sort.bam \
    24. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988163_sort.bam \
    25. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507080_sort.bam \
    26. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527957_sort.bam \
    27. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527958_sort.bam \
    28. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978599_sort.bam \
    29. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979787_sort.bam \
    30. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988166_sort.bam \
    31. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507079_sort.bam \
    32. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988165_sort.bam \
    33. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2179540_sort.bam \
    34. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527959_sort.bam \
    35. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988157_sort.bam \
    36. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507087_sort.bam \
    37. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527960_sort.bam \
    38. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988156_sort.bam \
    39. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507086_sort.bam \
    40. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507089_sort.bam \
    41. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527961_sort.bam \
    42. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527962_sort.bam \
    43. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527963_sort.bam \
    44. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527964_sort.bam \
    45. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5054727_sort.bam \
    46. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507090_sort.bam \
    47. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR1527965_sort.bam \
    48. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR2179541_sort.bam \
    49. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978602_sort.bam \
    50. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979790_sort.bam \
    51. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988189_sort.bam \
    52. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507066_sort.bam \
    53. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978603_sort.bam \
    54. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978605_sort.bam \
    55. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979792_sort.bam \
    56. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988155_sort.bam \
    57. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507121_sort.bam \
    58. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR978606_sort.bam \
    59. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR979793_sort.bam \
    60. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988170_sort.bam \
    61. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR6507075_sort.bam \
    62. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988176_sort.bam \
    63. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_ERR466186_sort.bam \
    64. --bam /shared5/studentprojects/Qikai/Horse_database/fixmate_File/markdup_possort_fixmate_SRR5988188_sort.bam \
    --referenceFasta /shared5/studentprojects/Qikai/Horse_database/EquCab3_ref/GCF_002863925.1_EquCab3.0_genomic.fna \
    --runDir Result_Franches_Montagnes